<?php

/**
 * @file
 * Contains bookmark.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Cache\Cache;

/**
 * Implements hook_help().
 */
function bookmark_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bookmark module.
    case 'help.page.bookmark':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bookmarks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bookmark_theme() {
  $theme = [];
  $theme['bookmarks'] = [
    'render element' => 'elements',
    'template' => 'bookmarks',
  ];
  $theme['bookmarks_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bookmark_theme_suggestions_bookmarks(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#bookmarks'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'bookmarks__' . $sanitized_view_mode;
  $suggestions[] = 'bookmarks__' . $entity->bundle();
  $suggestions[] = 'bookmarks__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'bookmarks__' . $entity->id();
  $suggestions[] = 'bookmarks__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function bookmark_entity_extra_field_info() {
  $bookmarks = \Drupal::service('bookmark')->getAllBookmarkTypes();
  $extra = [];
  foreach ($bookmarks as $bookmark) {
    /** @var \Drupal\bookmark\Entity\BookmarksTypeInterface $bookmark */
    $bundles = $bookmark->getApplicableBundles();
    foreach ($bundles as $bundle) {
      $extra['node'][$bundle]['display']['bookmarks_' . $bookmark->id()] = [
        'label' => t('Bookmark: %title', [
          '%title' => $bookmark->label(),
        ]),
        'description' => t('Bookmark link'),
        'weight' => 10,
      ];
    }
  }
  return $extra;
}

/**
 * Implements hook_entity_view().
 *
 * Display the link to bookmark a page.
 */
function bookmark_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Don't show on previews.
  if ($entity->isNew()) {
    return;
  }

  $build['#cache']['contexts'][] = 'user.permissions';

  if (empty($build['#cache']['tags'])) {
    $build['#cache']['tags'] = [];
  }

  // Get all possible bookmarks for this entity type.
  $bookmark_service = \Drupal::service('bookmark');
  $bookmarks = $bookmark_service->getAllBookmarkTypes($entity->bundle());

  foreach ($bookmarks as $bookmark) {
    /** @var \Drupal\bookmark\Entity\BookmarksTypeInterface $bookmark */
    //$build['#cache']['tags'] = Cache::mergeTags($build['#cache']['tags'], $bookmark->getCacheTags());
//    $build['bookmark_' . $bookmark->id()] = [
//      '#lazy_builder' => ['bookmark.link_builder:build', [
//        $entity->getEntityTypeId(),
//        $entity->id(),
//        $bookmark->id(),
//      ]],
//      '#create_placeholder' => TRUE,
//    ];
    $build['bookmark_' . $bookmark->id() . $bookmark->getEntityTypeId()] = $bookmark_service->generateLink($bookmark, $entity);
  }
}
