<?php

/**
 * @file
 * Contains bookmark.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function bookmark_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bookmark module.
    case 'help.page.bookmark':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bookmark') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bookmark_theme() {
  $theme = [];
  $theme['bookmarks_list'] = [
    'variables' => ['bookmarks' => NULL],
  ];
  $theme['bookmark'] = [
    'render element' => 'elements',
    'template' => 'bookmarks',
  ];
  $theme['bookmarks_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
  ];
  $theme['bookmark_link'] = [
    'variables' => ['link' => NULL],
  ];
  return $theme;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function bookmark_theme_suggestions_bookmark(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#bookmark'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'bookmark__' . $sanitized_view_mode;
  $suggestions[] = 'bookmark__' . $entity->bundle();
  $suggestions[] = 'bookmark__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'bookmark__' . $entity->id();
  $suggestions[] = 'bookmark__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function bookmark_entity_extra_field_info() {
  $bookmark_types = \Drupal::service('bookmark')->getAllBookmarkTypes();
  $extra = [];
  foreach ($bookmark_types as $bookmark_type) {
    /** @var \Drupal\bookmark\Entity\BookmarkTypeInterface $bookmark */
    $bundles = $bookmark_type->getApplicableBundles();
    foreach ($bundles as $bundle) {
      $extra['node'][$bundle]['display']['bookmark_' . $bookmark_type->id()] = [
        'label' => t('Bookmark: %title', [
          '%title' => $bookmark_type->label(),
        ]),
        'description' => t('Bookmark link'),
        'weight' => 10,
      ];
    }
  }
  return $extra;
}

/**
 * Implements hook_entity_view().
 *
 * Display the link to bookmark a page.
 */
function bookmark_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Don't show on previews.
  if ($entity->isNew()) {
    return;
  }

  $build['#cache']['contexts'][] = 'user.permissions';

  if (empty($build['#cache']['tags'])) {
    $build['#cache']['tags'] = [];
  }

  // Get all possible bookmark types for this entity type.
  /** @var \Drupal\bookmark\BookmarkService $bookmark_service */
  $bookmark_service = \Drupal::service('bookmark');
  $bookmark_types = $bookmark_service->getAllBookmarkTypes($entity->bundle());
  $user = \Drupal::currentUser();

  foreach ($bookmark_types as $bookmark_type) {
    $access = \Drupal::entityManager()->getAccessControlHandler('bookmark')->createAccess($bookmark_type->id(), $user, [], TRUE);
    if ($access->isAllowed() && $display->getComponent('bookmark_' . $bookmark_type->id())) {
      $build['bookmark_' . $bookmark_type->id()] = $bookmark_service->generateLink($bookmark_type, $entity, $user);
    }
  }
}
