<?php

/**
 * @file
 * Contains bookmark.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bookmark_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bookmark module.
    case 'help.page.bookmark':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bookmarks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bookmark_theme() {
  $theme = [];
  $theme['bookmarks'] = [
    'render element' => 'elements',
    'file' => 'bookmarks.page.inc',
    'template' => 'bookmarks',
  ];
  $theme['bookmarks_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'bookmarks.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function bookmark_theme_suggestions_bookmarks(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#bookmarks'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'bookmarks__' . $sanitized_view_mode;
  $suggestions[] = 'bookmarks__' . $entity->bundle();
  $suggestions[] = 'bookmarks__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'bookmarks__' . $entity->id();
  $suggestions[] = 'bookmarks__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}

/**
 * Implements hook_entity_extra_field_info().
 */
function bookmark_entity_extra_field_info() {
  $bookmarks = \Drupal::service('bookmark')->getAllBookmarkTypes();
  $extra = [];
  foreach ($bookmarks as $bookmark) {
    /** @var \Drupal\bookmark\Entity\BookmarksTypeInterface $bookmark */
    $bundles = $bookmark->getApplicableBundles();
    foreach ($bundles as $bundle) {
      $extra['node'][$bundle]['display']['bookmarks_' . $bookmark->id()] = [
        'label' => t('Bookmark: %title', [
          '%title' => $bookmark->label(),
        ]),
        'description' => t('Bookmark link'),
        'weight' => 10,
      ];
    }
  }
  return $extra;
}
