bookmark.bookmarks_type.*:
  type: config_entity
  label: 'Bookmarks type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    link_text:
      type: string
      label: 'Link text'
    bundles:
      type: sequence
      label: 'The entity bundles this flag applies to'
      sequence:
        - type: string
